### ISSUE TITLE
Video processing crashes on old devices

### ISSUE THREAD

**Issue by Bensge** [coolstar/RecordMyScreen#1]
I tried the app on my ipod touch 4g with ios 6.0,
however the app crashes when stopping the video because of too low free memory.
It doesn't matter how long the video is, the app always seems to crash.
Maybe some more optimisation is possible to use a little fewer memory in the video composing method?

**Comment by coolstar** [comment]
hmm, it works fine on my ipod touch 5 with ios 6.0.1
I'll have to test it on my ipod touch 3g and see.
It does use hardware accelerated h.264 encoding, so it should faster than normal CPU encoding

**Comment by coolstar** [comment]
Hopefully this https://github.com/coolstar/RecordMyScreen/commit/9ffb69afacea67d78365b2f33def399a364bed68 has fixed it. Please pull the latest version and test.

**Comment by coolstar** [comment]
Just tried it on my iPod touch 3G and it works fine.
