### ISSUE TITLE
Not Running

### ISSUE THREAD

**Issue by ASKProducts** [coolstar/RecordMyScreen#14]
When I run the application, it builds and installs the app, but it doesn't run the app and gives me this message:

No such file or directory (/Users/AKaufer/Library/Developer/Xcode/DerivedData/RecordMyScreen-colaqzfhwqmzpzctrpsavefigyac/Build/Products/Debug-iphoneos/RecordMyScreen.app/RecordMyScreen)

**Comment by ASKProducts** [comment]
Also, when i press "video.mp4" the movie thing shows up and immediately dissapears

**Comment by coolstar** [comment]
Please give more details as to the exact device model, firmware, and whether you're jailbroken or not.

**Comment by ASKProducts** [comment]
ipad 3, not jailbroken, ios 6

**Comment by coolstar** [comment]
There's an issue with recording the screen on iPad's on iOS 6. I'll update the readme now, and take a look at it.
We're gradually adding support for more devices.

**Comment by ASKProducts** [comment]
I know that, but is that connected to the fact that it will install but it won't run?

**Comment by coolstar** [comment]
That means XCode must be texting you! Lol, just try again :P

**Comment by coolstar** [comment]
Ok, I updated the readme.
