### ISSUE TITLE
Crash on Record (iPhone)

### ISSUE THREAD

**Issue by loretoparisi** [coolstar/RecordMyScreen#15]
I've got a crash at line 300 of CSRecordViewController.m 

```
if (buffers.count == 0)
    rawDataObj = [NSMutableData dataWithBytes:baseAddr length:totalBytes];
```

The crash is a BAD_EXEC

The last logs was:

2013-01-16 00:39:23.419 RecordMyScreen[2903:907] [MPAVController] Autoplay: Skipping autoplay, not enough buffered to keep up.
2013-01-16 00:39:25.422 RecordMyScreen[2903:510f] -[**NSMallocBlock** count]: unrecognized selector sent to instance 0x2080b0c0
2013-01-16 00:39:25.425 RecordMyScreen[2903:510f] **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[**NSMallocBlock** count]: unrecognized selector sent to instance 0x2080b0c0'
**\* First throw call stack:
(0x3814a3e7 0x34b82963 0x3814df31 0x3814c64d 0x380a4208 0x567c9 0x55c4d 0x3181d793 0x31821657 0x318217d9 0x342387f1 0x34238684)
libc++abi.dylib: terminate called throwing an exception

Also the audio is not being recorded from the MPMediaPlayer

Regression:
iPhone 5
iOS 6

**Comment by coolstar** [comment]
Not sure what the bug is on iPhone 5, and I don't have one to test on.
However, it works fine on my iPod touch 5 running iOS 6.

**Comment by loretoparisi** [comment]
So, I did two tests.

Test A.

 Trying to record audio from a app that is using AudioQueues where the queue has play and record and mix with others settings:

```
     UInt32 sessionCategory = kAudioSessionCategory_PlayAndRecord;
AudioSessionSetProperty (kAudioSessionProperty_AudioCategory,
                         sizeof (sessionCategory),
                         &sessionCategory);

UInt32 allowMixing = true;
AudioSessionSetProperty (kAudioSessionProperty_OverrideCategoryMixWithOthers,
                         sizeof (allowMixing),                             
                         &allowMixing);

OSStatus error = AudioSessionAddPropertyListener(kAudioSessionProperty_AudioRouteChange, propListener, self);
```

Test B.
Trying to record a audio from the Music/iPod player app.

**Comment by coolstar** [comment]
There is no way to record from the speakers. If you want to record from the speakers, I'd suggest hooking up some crazy wiring on the headphone jack to act like a "Stereo Mix" mic input

**Comment by Bensge** [comment]
Maybe audio recording is possible with some private API.
For example AirPlay Mirroring also transfers all device audio, maybe this API could be used for recording too

**Comment by coolstar** [comment]
Ok, the original bug has been fixed quite some time. Please open a new thread with the audio capturing feature request.

**Comment by loretoparisi** [comment]
Ok guys, thanks going to add a feature request so.
