### ISSUE TITLE
Crashes on second record

### ISSUE THREAD

**Issue by FD-** [coolstar/RecordMyScreen#16]
Crashes with an EXC_BAD_ACCESS on every second recording on my non-jailbroken iPod Touch 5G running iOS 6.0.1. It crashes immediately after I press the record button the second time.
The first recording works without any problems.

![RecordMyScreenCrash](https://f.cloud.github.com/assets/3320822/81236/bbcd668a-6307-11e2-8b0e-43fd1d90ee40.png)

EDIT: It seems to crash in captureShot:
![Bildschirmfoto 2013-01-20 um 14 51 06](https://f.cloud.github.com/assets/3320822/81239/b3c80f5c-6308-11e2-8887-af134dd540d2.png)

EDIT 2: Same crash on 1st Gen iPad.

**Comment by coolstar** [comment]
I've been able to reproduce the issue here, so I'll debug it and see.

**Comment by coolstar** [comment]
This has been fixed as of https://github.com/coolstar/RecordMyScreen/commit/374f12dea25ba078f829dd397318b77dea0c595b

It turned out to be a missing retain statement
