### ISSUE TITLE
Recordings rotated

### ISSUE THREAD

**Issue by FD-** [coolstar/RecordMyScreen#17]
Although recording works on the 1st Gen iPad, the resulting videos are rotated 180 degrees.

EDIT: It seems like videos on my iPod 5G are always assumed to be portrait and videos of the iPad are assumed to be landscape (home button right).

**Comment by coolstar** [comment]
This is actually due to the framebuffer of the iPad being weird. It assumes it's portrait on all devices, but the framebuffer makes it all weird.

**Comment by rmurray68** [comment]
I have the same experience on iPad 2 with IOS 6.1  Recording is rotated 180 degrees.

**Comment by coolstar** [comment]
Ok, you can try playing with the AVAssetWriter's settings by following this article: http://stackoverflow.com/questions/8203333/rotate-avassetwriters-output-180-deg-about-the-x-axis
Do it in your own fork of this repository, and then send me a pull request :)

**Comment by coolstar** [comment]
Hopefully 0b4de19b9a26ddc8d496e0ff5989d167d1ba934b has alleviated the issue to some extent. Try setting the orientation in the settings and tell me which one suits you best. Note that the end orientation must be Portrait with the home button at the bottom.

**Comment by rmurray68** [comment]
The latest code with the Orientation settings does help. It is kind of odd, but here is a working combination on the iPad2 (IOS 6.1.2)
- Portrait - Orientation Setting is Landscape (Home Button on the Right)
- Landscape (Home Button on the right) - Orientation Setting is Portrait Upside Down

**Comment by allwinpasu** [comment]
i am using iPad 2 with IOS 6.1 Recording is rotated 180 degrees.and the iPad 3  video width cut 50%

**Comment by coolstar** [comment]
Just tested the latest beta (currently binary only until I resolve legal issues with xRec) and the orientation settings are fixed on my iPad mini.
