### ISSUE TITLE
can't view recorded video on iPad2

### ISSUE THREAD

**Issue by hash3r** [coolstar/RecordMyScreen#18]
![IMG_0054 1](https://f.cloud.github.com/assets/1092925/114802/07908c82-6bb4-11e2-974a-9ac4b7ad61b1.PNG)
all my videos have a size 144kb

**Comment by coolstar** [comment]
What iOS version?

**Comment by Baddaboo** [comment]
I'm having the same issue on iOS 6.0.1

**Comment by hash3r** [comment]
iOS 5.1

**Comment by coolstar** [comment]
Try recording again on the latest version of RecordMyScreen, as it may have been the integer overflow, which I have fixed.

**Comment by rmurray68** [comment]
Recording works now on iPad 2 with IOS 6.1    In process to upgrade to IOS 6.1.2 to confirm

**Comment by coolstar** [comment]
Ok, since recording works on iPad 2, and you can watch the video, I shall close this issue.
