### ISSUE TITLE
running unjailbroken

### ISSUE THREAD

**Issue by favna** [coolstar/RecordMyScreen#22]
I saw this as a tweak on cydia, however I would also like to be able to run it on an iPhone which I can't jailbreak because it is my phone of my work. I can't find it in the appstore, also I don't have access to an apple pc for xcode. Is there any way I could get an ipa file to install through itunes?

**Comment by JagravNaik** [comment]
I have Xcode and when I clicked on run it said build failed is there a way I can fix it?
—

**Comment by coolstar** [comment]
@jcgames there is no way to simply install an ipa file on a non-jailbroken device. You need a developer account.
@JagravNaik Are you building for the Simulator? RecordMyScreen uses APIs that are present on actual iOS Devices, but not on the simulator.
