### ISSUE TITLE
Red Bar Gone in Latest Build

### ISSUE THREAD

**Issue by coolstar** [coolstar/RecordMyScreen#28]
On the latest commit, it appears as if the red bar disappeared. Can anyone else confirm this?

**Comment by KennyTangHK** [comment]
iPod Touch 4 iOS 6.0
No red bar anymore! Great!
But I didn't update the app from Cydia, it's amazing!!!

**Comment by mashhoodr** [comment]
@coolstar is this some setting just for inapp or when the app goes in the background as well? Im using the iPod Touch 5G with iOS6.1, the red bar is showing when the app goes in background, any way to disable that? I tried doing that by disabling the audio, but that starts corrupting the video files..

**Comment by coolstar** [comment]
It's for backgrounding as well. Are you using the latest build from github, or the one from Cydia? With this one I don't get a red bar even in safe mode, hence why I think it's due to code changes in RecordMyScreen. I can't unjailbreak though as that would force me to 6.1.3, which is like the end of the world for me :P
—

**Comment by mashhoodr** [comment]
Im using the latest version from Github, and my device is currently non-jail broken (this is important for me). Can you please point me towards the code which could be related to hiding the bar? Thanks! 
[ps. AWESOME work on the library :+1:]

**Comment by coolstar** [comment]
I believe it shouldn't show the red bar when you background the app on default settings, as far as my testing went.
—

**Comment by canvasding** [comment]
Hi coolstar，
I downloaded the lastest version and build for unjailbreak device. But I still get red bar when running background.  Do I miss anything for getting rid of red bar?

**Comment by canvasding** [comment]
I tried to build recordmyscreentweak with theos, but I got the bellow issues. Please give some advice, thanks in advance!

/Users/user/Documents/rufusding/iOS/RecordMyScreen/recordmyscreentweak/theos/makefiles/targets/Darwin/iphone.mk:46: Deploying to iOS 3.0 while building for 6.0 will generate armv7-only binaries.
Making all for tweak RecordMyScreenTweak...
 Compiling ActivatorListener.mm...
 Compiling ../RecordMyScreen/CSScreenRecorder.m...
../RecordMyScreen/CSScreenRecorder.m:269:5: error: implicit declaration of
      function 'IOSurfaceLock' is invalid in C99
      [-Werror,-Wimplicit-function-declaration]
    IOSurfaceLock(_surface, 0, nil);
    ^
../RecordMyScreen/CSScreenRecorder.m:273:5: error: implicit declaration of
      function 'IOSurfaceUnlock' is invalid in C99
      [-Werror,-Wimplicit-function-declaration]
    IOSurfaceUnlock(_surface, 0, 0);
    ^
../RecordMyScreen/CSScreenRecorder.m:273:5: note: did you mean 'IOSurfaceLock'?
    IOSurfaceUnlock(_surface, 0, 0);
    ^~~~~~~~~~~~~~~
    IOSurfaceLock
../RecordMyScreen/CSScreenRecorder.m:269:5: note: 'IOSurfaceLock' declared here
    IOSurfaceLock(_surface, 0, nil);
    ^
../RecordMyScreen/CSScreenRecorder.m:276:22: error: implicit declaration of
      function 'IOSurfaceGetBaseAddress' is invalid in C99
      [-Werror,-Wimplicit-function-declaration]
    void _baseAddr = IOSurfaceGetBaseAddress(_surface);
                     ^
../RecordMyScreen/CSScreenRecorder.m:276:11: error: incompatible integer to
      pointer conversion initializing 'void *' with an expression of type 'int'
      [-Werror,-Wint-conversion]
    void *baseAddr = IOSurfaceGetBaseAddress(_surface);
          ^          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../RecordMyScreen/CSScreenRecorder.m:314:9: error: implicit declaration of
      function 'CVPixelBufferLockBaseAddress' is invalid in C99
      [-Werror,-Wimplicit-function-declaration]
        CVPixelBufferLockBaseAddress(pixelBuffer, 0);
        ^
../RecordMyScreen/CSScreenRecorder.m:315:27: error: implicit declaration of
      function 'CVPixelBufferGetBaseAddress' is invalid in C99
      [-Werror,-Wimplicit-function-declaration]
        void *pixelData = CVPixelBufferGetBaseAddress(pixelBuffer);
                          ^
../RecordMyScreen/CSScreenRecorder.m:315:27: note: did you mean
      'CVPixelBufferLockBaseAddress'?
        void *pixelData = CVPixelBufferGetBaseAddress(pixelBuffer);
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
                          CVPixelBufferLockBaseAddress
../RecordMyScreen/CSScreenRecorder.m:314:9: note: 
      'CVPixelBufferLockBaseAddress' declared here
        CVPixelBufferLockBaseAddress(pixelBuffer, 0);
        ^
../RecordMyScreen/CSScreenRecorder.m:315:15: error: incompatible integer to
      pointer conversion initializing 'void *' with an expression of type 'int'
      [-Werror,-Wint-conversion]
        void *pixelData = CVPixelBufferGetBaseAddress(pixelBuffer);
              ^           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../RecordMyScreen/CSScreenRecorder.m:326:9: error: implicit declaration of
      function 'CVPixelBufferUnlockBaseAddress' is invalid in C99
      [-Werror,-Wimplicit-function-declaration]
        CVPixelBufferUnlockBaseAddress(pixelBuffer, 0);
        ^
../RecordMyScreen/CSScreenRecorder.m:326:9: note: did you mean
      'CVPixelBufferLockBaseAddress'?
        CVPixelBufferUnlockBaseAddress(pixelBuffer, 0);
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        CVPixelBufferLockBaseAddress
../RecordMyScreen/CSScreenRecorder.m:314:9: note: 
      'CVPixelBufferLockBaseAddress' declared here
        CVPixelBufferLockBaseAddress(pixelBuffer, 0);
        ^
../RecordMyScreen/CSScreenRecorder.m:358:64: error: use of undeclared identifier
      'kIOSurfaceIsGlobal'
  ...[NSNumber numberWithBool:YES], kIOSurfaceIsGlobal,
                                    ^
../RecordMyScreen/CSScreenRecorder.m:368:12: error: implicit declaration of
      function 'IOSurfaceCreate' is invalid in C99
      [-Werror,-Wimplicit-function-declaration]
    return IOSurfaceCreate((CFDictionaryRef)properties);
           ^
../RecordMyScreen/CSScreenRecorder.m:368:12: error: incompatible integer to
      pointer conversion returning 'int' from a function with result type
      'IOSurfaceRef' (aka 'struct __IOSurface *') [-Werror,-Wint-conversion]
    return IOSurfaceCreate((CFDictionaryRef)properties);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../RecordMyScreen/CSScreenRecorder.m:375:26: error: use of undeclared identifier
      'UIScreen'
    CGRect screenRect = [UIScreen mainScreen].bounds;
                         ^
../RecordMyScreen/CSScreenRecorder.m:376:20: error: use of undeclared identifier
      'UIScreen'
    float scale = [UIScreen mainScreen].scale;
                   ^
../RecordMyScreen/CSScreenRecorder.m:379:11: error: use of undeclared identifier
      'UIDevice'
    if ([[UIDevice currentDevice] userInterfaceIdiom] ==...
          ^
../RecordMyScreen/CSScreenRecorder.m:379:58: error: use of undeclared identifier
      'UIUserInterfaceIdiomPhone'
  ...currentDevice] userInterfaceIdiom] == UIUserInterfaceIdiomPhone) {
                                           ^
../RecordMyScreen/CSScreenRecorder.m:446:63: error: use of undeclared identifier
      'kCVPixelFormatType_32BGRA'; did you mean 'kCMPixelFormat_32BGRA'?
  ...[NSNumber numberWithInt:kCVPixelFormatType_32BGRA],...
                             ^~~~~~~~~~~~~~~~~~~~~~~~~
                             kCMPixelFormat_32BGRA
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS6.1.sdk/System/Library/Frameworks/CoreMedia.framework/Headers/CMFormatDescription.h:505:2: note: 
      'kCMPixelFormat_32BGRA' declared here
        kCMPixelFormat_32BGRA                   = 'BGRA',
        ^
../RecordMyScreen/CSScreenRecorder.m:446:91: error: use of undeclared identifier
      'kCVPixelBufferPixelFormatTypeKey'
  ...[NSNumber numberWithInt:kCVPixelFormatType_32BGRA], k...
                                                         ^
17 errors generated.
make[2]: *_\* [.theos/obj/../RecordMyScreen/CSScreenRecorder.m.730127ff.o] Error 1
make[1]: **\* [internal-library-all_] Error 2
make: **\* [RecordMyScreenTweak.all.tweak.variables] Error 2

**Comment by holgersindbaek** [comment]
I also still get the red bar on an iPod touch 5g, running 6.1.3. 

The red bar doesn't show in the app itself, but when you go out it it, then it shows. 

It's a really awesome app you have here. Is it something that can be fixed?

**Comment by mashhoodr** [comment]
@holgersindbaek I fixed this issue on my iPod 5g (non jail broken) by disabling the audio recording.

**Comment by holgersindbaek** [comment]
@mashhoodr How did you disable the audio recording?

**Comment by mashhoodr** [comment]
you need to comment out the setupAudio call (line115 in CSScreenRecorder.m). That should do it.

**Comment by coolstar** [comment]
@mashhoodr @holgersindbaek are you guys sure that backgrounding works with audio recording disabled?

**Comment by holgersindbaek** [comment]
@mashhoodr @coolstar It doesn't! Tried to comment out line 115. Seems like I can record videos, but when I press them in the app afterwards, then they don't open.

And sometimes the app crashes when I go into the app again (when still recording) and recording stops.

Can it really be true that there's no solution for this? This is an awesome tool for making a screencast, but with the red bar, then it's not very usable!

**Comment by FD-** [comment]
I guess that's because only the audio recording keeps the app running in background. 
My suggestion would be to endlessly play an empty mp3 in background and keep the app running in background via AVAudioPlayer.
Here is how to implement it: http://mobile.tutsplus.com/tutorials/iphone/ios-sdk_background-audio/

The red bar would be gone, just the white playing triangle will be shown in the status bar, which should at least be less annoying than the red bar.
Note that recording won't work then. I suggest adding that as an additional mode and let the user choose which one to use.

I already had implemented that in a local copy of the project some months ago (never published it) and it worked well if I remember right.

**Comment by coolstar** [comment]
@holgersindbaek hmm, looks like it just doesn't show the red bar for me. I guess the explanation for it not showing on my iPod touch 5 (6.1.2) would probably be that I have RecordMyScreen in /Applications instead of /var/mobile/Applications/xxx/

It is necessary for audio recording to be present for iOS to keep the app running. Without it, iOS suspends the app, and the video gets corrupted because the frames can't be recorded when it's suspended.

**Comment by holgersindbaek** [comment]
@coolstar Hmmm ok. How can I get it into /Applications, when I'm building from xCode?  

## 

All the best

Holger Sindbaek
Holgersindbaek.com (http://Holgersindbaek.com)

Co-founder
Uninkd.com (http://Uninkd.com)
Meer.li (http://Meer.li)

**Comment by coolstar** [comment]
@holgersindbaek I only have it in /Applications because my developer cert. expired, so I had to copy it there over SSH after fake-codesigning (requires jailbreak)

**Comment by holgersindbaek** [comment]
@coolstar Damn… My iPod Touch is not jailbroken 6.1.3 and it seems like a big hassle to jailbreak 6.1.3!

You sure there's no solution to getting rid of the red bar when compiling from xCode?  

## 

All the best

Holger Sindbaek
Holgersindbaek.com (http://Holgersindbaek.com)

Co-founder
Uninkd.com (http://Uninkd.com)
Meer.li (http://Meer.li)

**Comment by mashhoodr** [comment]
@holgersindbaek oh sorry. I made additional modifications which keeps my app alive in the background. I guess playing a MP3 in the background should work..

**Comment by holgersindbaek** [comment]
@coolstar Hmmm… trying to play a song from iTunes, while recording, but it seems to be same story. I've also commented out line 115. Should I comment it back in?

## 

All the best

Holger Sindbaek
Holgersindbaek.com (http://Holgersindbaek.com)

Co-founder
Uninkd.com (http://Uninkd.com)
Meer.li (http://Meer.li)

**Comment by FD-** [comment]
No, leave it commented out. Did you add the entry for playing audio in background in your info.plist?

Here is the code I used for starting the audio:
   -(void)playAudio {

```
NSURL *url=[NSURL fileURLWithPath:[[NSBundle mainBundle] pathForResource:@"mute500ms" ofType:@"caf"]];
_audioPlayer = [[AVAudioPlayer alloc] initWithContentsOfURL:url error:nil];
[_audioPlayer setNumberOfLoops:-1]; //Endlessly loops



// Registers this class as the delegate of the audio session to listen for audio interruptions
[[AVAudioSession sharedInstance] setDelegate: self];
//Set the audio category of this app to playback.
NSError *setCategoryError = nil;

[[AVAudioSession sharedInstance]
 setCategory: AVAudioSessionCategoryPlayback error: &setCategoryError];
if (setCategoryError) {
}

// Registers the audio route change listener callback function
// An instance of the audio player/manager is passed to the listener
//AudioSessionAddPropertyListener ( kAudioSessionProperty_AudioRouteChange,audioRouteChangeListenerCallback, self );

//Activate the audio session
NSError *activationError = nil;
[[AVAudioSession sharedInstance] setActive: YES error: &activationError];
if (activationError) {
}

[_audioPlayer prepareToPlay];
[_audioPlayer play];
```

   }

**Comment by holgersindbaek** [comment]
@FD- @coolstar I have the "App plays audio" as the required background mode, if that's what you mean.

Where you would you put the playAudio function? What are you using it instead of?

**Comment by coolstar** [comment]
If you would mind sending it in as a pull request, I can pull it in upstream.

**Comment by FD-** [comment]
@holgersindbaek Yes, that's what I meant.
playAudio was called when starting the recording, but unfortunately, I cannot find the whole project anymore, so I cannot tell you the exact details.

**Comment by holgersindbaek** [comment]
@FD- @coolstar  Ok... wouldn't it essentially do the same thing as having an mp3 play in the background? Doesn't seem like the solution?

**Comment by aqeeliqbal** [comment]
from the code provided i compiled and installed the app on iPhone 4S iOS 6.1.3
still having red bad while recording.

how to fix this??
