### ISSUE TITLE
Install?

### ISSUE THREAD

**Issue by ghost** [coolstar/RecordMyScreen#3]
I'm a noob to Xcode, I used my provisioning profile and tried to build it, but get this error.

(null): Framework not found IOSurface

**Comment by coolstar** [comment]
That error is because you're trying to run it on the simulator, which doesn't work.
You must run it on a device.

**Comment by sangshuduo** [comment]
IOSurface is private framework. So no way to get approve by appstore, right?

**Comment by Bensge** [comment]
Nope, no way.
The Display Recorder apps that made their way to the Appstore were hiding their usage of private frameworks, however apple found out somewhen and kicked them
