### ISSUE TITLE
IASKAppSettingsViewController.h

### ISSUE THREAD

**Issue by Niramo** [coolstar/RecordMyScreen#33]
It says 'IASKAppSettingsViewController.h' file not found, could you upload it and give me a Download? (I'm swiss sorry for bad English).

**Comment by mashhoodr** [comment]
@Niramo : IASKAppSettings is a git submodule to the project, please try cloning with initialize submodules parameters, or clone https://github.com/futuretap/InAppSettingsKit separately and add it to the InAppSettingsKit folder.

**Comment by Niramo** [comment]
Thanks for your help, now everything's fine, but there is one more error:
"Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang failed with exit code 1"???

**Comment by mashhoodr** [comment]
Clean and build should do the trick..
