### ISSUE TITLE
RecordMyScreen source code compile issue ---ld: framework not found IOSurface

### ISSUE THREAD

**Issue by canvasding** [coolstar/RecordMyScreen#35]
Dear all,
I am new to iOS.  I have no idea whether is suitable  to post this issue. If not, please info me to delete it. Thanks in advance!
After downloaded "RecordMyScreen" from github, I tried to build it. But I encountered an issue while compiling. Could you please give some advice how to fixed it?

I already install iOSOpenDev successfully.
My Mac OS X is lion 10.7.5, Xcode 4.6.2 (iOS 6.1)
try to add private framework from link binaries from library(from iOS 6.1) or link binaries from library(from other like iOSOpenDev framework), but still got the same issue.
## Issue Log:

Ld /Users/user/Library/Developer/Xcode/DerivedData/RecordMyScreen-dlwucvtqjaaetdcesjbmwqryvkxk/Build/Products/Release-iphonesimulator/RecordMyScreen.app/RecordMyScreen normal i386

```
cd /Users/user/Documents/rufusding/iOS/recordMyscreenIpadMini/RecordMyScreen-master

setenv IPHONEOS_DEPLOYMENT_TARGET 5.0

setenv PATH "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin"

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch i386 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.1.sdk -L/Users/user/Library/Developer/Xcode/DerivedData/RecordMyScreen-dlwucvtqjaaetdcesjbmwqryvkxk/Build/Products/Release-iphonesimulator -F/Users/user/Library/Developer/Xcode/DerivedData/RecordMyScreen-dlwucvtqjaaetdcesjbmwqryvkxk/Build/Products/Release-iphonesimulator -F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.1.sdk/System/Library/PrivateFrameworks -F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.1.sdk/System/Library/PrivateFrameworks -filelist /Users/user/Library/Developer/Xcode/DerivedData/RecordMyScreen-dlwucvtqjaaetdcesjbmwqryvkxk/Build/Intermediates/RecordMyScreen.build/Release-iphonesimulator/RecordMyScreen.build/Objects-normal/i386/RecordMyScreen.LinkFileList -Xlinker -objc_abi_version -Xlinker 2 -framework IOSurface -framework CoreSurface -framework IOMobileFramebuffer -framework IOKit -fobjc-link-runtime -Xlinker -no_implicit_dylibs -mios-simulator-version-min=5.0 -framework AVFoundation -framework CoreGraphics -framework CoreMedia -framework CoreVideo -framework Foundation -framework GraphicsServices -framework MediaPlayer -framework MessageUI -framework QuartzCore -framework UIKit -o /Users/user/Library/Developer/Xcode/DerivedData/RecordMyScreen-dlwucvtqjaaetdcesjbmwqryvkxk/Build/Products/Release-iphonesimulator/RecordMyScreen.app/RecordMyScreen
```

ld: framework not found IOSurface

clang: error: linker command failed with exit code 1 (use -v to see invocation)

Best regards,

Cavasding

**Comment by canvasding** [comment]
When I tried iOS Device Not simulator, issue is solved.

**Comment by kujohn** [comment]
Im getting this problem even while targeting an actual iOS Device. My installation of iOSOpenDev failed, is it required?

**Comment by kujohn** [comment]
Got iOSOpenDev installed, linked the framework, targeted an ipod touch, still getting the error.

**Comment by kujohn** [comment]
The include references to IOSurface/*
Removing that fixes it.

**Comment by coolstar** [comment]
Fixed in the latest commit.

**Comment by amitsaxena688** [comment]
there is no need to install iOSOpenDev.
you can run the app on your devices. dont use simulators.
in my case this works fine on actual devices not on simulators.
