### ISSUE TITLE
video & audio not sync. 

### ISSUE THREAD

**Issue by jallens** [coolstar/RecordMyScreen#39]
when you recording 100s duration.  you will find video & audio not sync.

**Comment by jallens** [comment]
i fix it.

in file : CSScreenRecorder.m     line : 516
add:
[compositionVideoTrack scaleTimeRange:CMTimeRangeMake(kCMTimeZero, videoAsset.duration) toDuration:audioAsset.duration];

**Comment by jallens** [comment]
should i pull request for you?

**Comment by PyroFilmsFX** [comment]
Is this in poll request? This is a needed fix!

**Comment by coolstar** [comment]
Fixed in the pull request merged just now.

**Comment by PyroFilmsFX** [comment]
Ok! Cool! Thanks!
