### ISSUE TITLE
Not recording OpenGL apps

### ISSUE THREAD

**Issue by gpambrozio** [coolstar/RecordMyScreen#4]
I'm trying to record an app that uses OpenGL to draw and I"m getting a black screen whenever I try to record it. Any ideas on how to fix this? Any pointers would be highly appreciated as it's next to impossible to find good documentation on the APIs you used.

Pretty cool project though. Thanks for sharing this!

**Comment by coolstar** [comment]
We're currently changing the app to encode on the fly, so OpenGL isn't a priority ATM. We'll look at it soon though :)

**Comment by gpambrozio** [comment]
I'd be happy to do it myself (and contribute back) but I'd need some pointers. If that's at all possible of course... Thanks.

**Comment by coolstar** [comment]
You'll need to know about how to use the AVFoundation Public framework, AVAssetWriter, AVAssetWriterInputPixelBufferAdaptor, AVAssetWriterInput, and/or the Private IOSurface and CoreSurface APIs.

**Comment by coolstar** [comment]
OpenGL is now fully supported in the latest build :)

**Comment by gpambrozio** [comment]
Works perfectly now! Thanks for the awesome work!
