### ISSUE TITLE
Audio/video out of sync!

### ISSUE THREAD

**Issue by PyroFilmsFX** [coolstar/RecordMyScreen#40]
I was talking to the developer of RecordScreen and he informed me of this apps new update. Becuae he was the one to merge the audio/video. He proceeded to tell me one of the users on this app explained how to fix the issue, and he added the fix to his own app. Works perfectly. But was the fix actually added to RecordMyScreen? If not, it is much appreciated!

**Comment by coolstar** [comment]
Merged the pull request.

**Comment by chosen11** [comment]
How do I download screen recorder? When I tap the link it says safari cannot download this :(
