### ISSUE TITLE
Why does RecordMyScreen have audio, but no video?

### ISSUE THREAD

**Issue by DJBarnard** [coolstar/RecordMyScreen#49]
I'm on iPad and whenever I go on the app and start recording, I play a game or something and when I stop the recording, it is only audio.

**Comment by coolstar** [comment]
I assume you're on an iPad with Retina display. Go to Settings > Video Size and set the video size to 50%.

**Comment by DJBarnard** [comment]
Thanks, I'll try that.

On 8 July 2013 22:38, coolstar notifications@github.com wrote:

> I assume you're on an iPad with Retina display. Go to Settings > Video
> Size and set the video size to 50%.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/coolstar/RecordMyScreen/issues/49#issuecomment-20638037
> .

## 

*Daniel Barnard
*

**Comment by DJBarnard** [comment]
On the app, or on my settings

**Comment by coolstar** [comment]
In the App Settings.
