### ISSUE TITLE
huge memory 

### ISSUE THREAD

**Issue by kimiwang** [coolstar/RecordMyScreen#50]
![2013-07-16 4 30 15](https://f.cloud.github.com/assets/3202484/803452/ff20da1e-edf1-11e2-9075-ab0baa7c4368.png)

**Comment by coolstar** [comment]
All I can say is that RecordMyScreen does heavyweight screen capture and video encoding at the same time, I don't think there is a way to decrease the memory usage as nothing is being leaked right now. If you do manage to optimize the app further, send a pull request and I'll take a look.
