### ISSUE TITLE
Recordmyscreen could not be installed at this time - please help :(

### ISSUE THREAD

**Issue by SkinnyFG** [coolstar/RecordMyScreen#51]
Please help when I try to download it stops halfway and says "recordmyscreen could not be installed at this time" I downloaded it perfectly, then I tried to download gba4ios, and it replaced it! I deleted gba4ios, then I downloaded recordmyscreen again. And it gave me that message :(

**Comment by coolstar** [comment]
This is an issue with the code signature used to sign it, not an issue with RecordMyScreen. Contact the place you downloaded it from, as this isn't something I can fix.
