### ISSUE TITLE
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang failed with exit code 1

### ISSUE THREAD

**Issue by iehsan77** [coolstar/RecordMyScreen#55]
hello,

I just tried this but i compiled i got this 

Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang failed with exit code 1

 #import "IASKAppSettingsViewController.h"   file not found 

Please let me know how i can find this OR send it to me on iehsan77@gmail.com  thanks

**Comment by coolstar** [comment]
Make sure you specify the "--recursive" argument when cloning with git.
