### ISSUE TITLE
How to start capture using activator?

### ISSUE THREAD

**Issue by Dudubitn** [coolstar/RecordMyScreen#56]
Hello
I'm trying to start a capture without entering the app recordmyscreen, when I creat a shortcut action in activator it's just open recordmyscreen .. How can I creat capture/ record action?

**Comment by Dudubitn** [comment]
I want to add another question.. When I tried to record video chat screen , the app crash all the time..thank you.

**Comment by coolstar** [comment]
The activator action was already done in the tweak version (source code is available, build it yourself for now).
