### ISSUE TITLE
iOS7 support

### ISSUE THREAD

**Issue by Shimon1981** [coolstar/RecordMyScreen#57]
Hi, 

Cool program!

In iOS7 it records only itself. When I switch to other screens, it stops recording.
Any chance you could check on that?

Thanks,
Shimon

**Comment by JanSebastian** [comment]
I'd also appreciate any feedback whether there will be an update. It has been a really helpful app!

**Comment by coolstar** [comment]
I am looking into iOS 7's frameworks now that it's been released for some time. However updates will be binary-only for reasons explained in another issue.

**Comment by favormm** [comment]
I have the same problem on iOS7. This project is stop to update?

**Comment by reizencroft** [comment]
Any tips on how to fix the iOS7 issue?

**Comment by coolstar** [comment]
This has been fixed in the latest binary release. (No source code. Re: #60)
