### ISSUE TITLE
XCode 5 - iOKit not found

### ISSUE THREAD

**Issue by jayztemplier** [coolstar/RecordMyScreen#58]
Hey there,

First of all, I want to say you guys have done an amazing job.

When I try to compile the project on XCode 5, it says IOKit not found, any idea?
Works well on XCode 4.6.

Thanks.

**Comment by amitsaxena688** [comment]
same problem here.
but i could run this app on ios7. i installed the app first then i updated io6 to ios7.
but there is a problem it cannot record properly now. it shows some black screen while you play a recorded video

**Comment by datalogen** [comment]
I also had the same problem - my solution, for now, was to copy the 6.1 sdk from xcode 4.6.3 to xcode 5.
So copy from xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/

**Comment by amitsaxena688** [comment]
Thanks datalogen,
if i do this and again i create some ios apps then will those app be running on ios7.?
actually i want ios7 support in recorder app.

**Comment by datalogen** [comment]
It will run fine on an iOS 7 device. Although you won't be able to use all the fancy new features of the 7.0 SDK in your apps. As I wrote, this is just a temporary solution ("for now"), until I or someone else comes up with a better solution.

**Comment by amitsaxena688** [comment]
i could solve the issue but one problem(black screen) is still here.
Thanks datalogen..!

**Comment by coolstar** [comment]
This is an issue with the framework being moved in the iOS 7 SDK. When I start supporting iOS 7, this issue will be fixed.

**Comment by JavanJie** [comment]
cd /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.0.sdk/System/Library/Frameworks/IOKit.framework
sudo ln -s Versions/A/IOKit .

That worked, but when running on iOS7 device, the app can only record itself's content.

I got it from this link:http://stackoverflow.com/questions/17542092/iokit-not-found

**Comment by anujbhambhani** [comment]
did we find any solution for the issue that the app can only record itself's content on ios 7.

**Comment by coolstar** [comment]
Fixed in the private build (Re: #60)
