### ISSUE TITLE
Weird recording screen

### ISSUE THREAD

**Issue by SuryaC** [coolstar/RecordMyScreen#61]
When I start recording and watch the recording the recording is pretty messed up here let me show u how it looks in this picture
![image](https://f.cloud.github.com/assets/5606486/1265036/9f13deea-2c68-11e3-8fc0-e6d71271a9ad.jpg)
There is like a weird thingy on the right side that messes up how it looks

**Comment by coolstar** [comment]
What model iPad are you running it on? Mini? 1? 2? 3? 4?

**Comment by SuryaC** [comment]
mini

**Comment by coolstar** [comment]
you'll need to update to the new binary release on Cydia, which fixes the iPad mini issue. Unfortunately I can't update the source code as @akinGames is probably still out to try and steal it.
