### ISSUE TITLE
IOKit/IOTypes.h file not found!

### ISSUE THREAD

**Issue by serkanerkan** [coolstar/RecordMyScreen#69]
![screen shot 2014-01-19 at 02 43 23](https://f.cloud.github.com/assets/2148760/1948671/bed37360-80a2-11e3-9d91-991e5c2e1734.png)

im getting theese errors.. can you help me ?

**Comment by Norod** [comment]
Just:

cd /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.0.sdk/System/Library/Frameworks/IOKit.framework/

Or in case you are using the latest beta (5.1 beta 3, at the moment):

cd /Applications/Xcode51-Beta3.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk/System/Library/Frameworks/IOKit.framework/

Then type:

sudo ln -s Versions/A/IOKit

This should fix the issue for you

**Comment by serkanerkan** [comment]
Thank you for your reply:)
