### ISSUE TITLE
"IOMobileFrameBuffer.h" file not found

### ISSUE THREAD

**Issue by kenpig** [coolstar/RecordMyScreen#70]
When I copy CSScreenRecorder file to Xcode5, it give me an error, information here:
"IOMobileFrameBuffer.h" file not found with <angled> include

![2014-03-26 2 50 46](https://f.cloud.github.com/assets/3032146/2522096/ff75aa6a-b4b8-11e3-9cd3-66a75a5e027a.png)

How can i fix that, Thank you.

**Comment by Norod** [comment]
Did you try https://github.com/coolstar/RecordMyScreen/issues/69 and it didn't work?

**Comment by kenpig** [comment]
I have tried, but still made the same error message xcode5

**Comment by kenpig** [comment]
![2014-03-26 4 01 11](https://f.cloud.github.com/assets/3032146/2522280/2b31e9f8-b4bd-11e3-8af9-47f749728e25.png)

In a new project.

**Comment by coolstar** [comment]
RecordMyScreen hasn't supported building via Xcode for a while now. Only theos is supported now.
